package com.vobot.rentals.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Dark Mode Colors
 */
val primaryDark = Color(0xFFFFAEDC)
val onPrimaryDark = Color(0xFF600049)
val primaryContainerDark = Color(0xFF880368)
val onPrimaryContainerDark = Color(0xFFFF92D4)
val secondaryDark = Color(0xFFFCB0DB)
val onSecondaryDark = Color(0xFF521C40)
val secondaryContainerDark = Color(0xFF6F3559)
val onSecondaryContainerDark = Color(0xFFEDA2CC)
val tertiaryDark = Color(0xFFFFB3B2)
val onTertiaryDark = Color(0xFF680012)
val tertiaryContainerDark = Color(0xFF8F1022)
val onTertiaryContainerDark = Color(0xFFFF9A99)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1A1016)
val onBackgroundDark = Color(0xFFF1DDE5)
val surfaceDark = Color(0xFF1A1016)
val onSurfaceDark = Color(0xFFF1DDE5)
val surfaceVariantDark = Color(0xFF54414B)
val onSurfaceVariantDark = Color(0xFFDAC0CB)
val outlineDark = Color(0xFFA28A96)
val outlineVariantDark = Color(0xFF54414B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF1DDE5)
val inverseOnSurfaceDark = Color(0xFF392D33)
val inversePrimaryDark = Color(0xFFA62881)
val surfaceDimDark = Color(0xFF1A1016)
val surfaceBrightDark = Color(0xFF42363C)
val surfaceContainerLowestDark = Color(0xFF150B11)
val surfaceContainerLowDark = Color(0xFF23191E)
val surfaceContainerDark = Color(0xFF271D22)
val surfaceContainerHighDark = Color(0xFF32272D)
val surfaceContainerHighestDark = Color(0xFF3D3137)


/**
 * Light Mode Colors
 */
val primaryLight = Color(0xFF610049)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF880368)
val onPrimaryContainerLight = Color(0xFFFF92D4)
val secondaryLight = Color(0xFF884A70)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFB2DD)
val onSecondaryContainerLight = Color(0xFF7C4065)
val tertiaryLight = Color(0xFF690013)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF8F1022)
val onTertiaryContainerLight = Color(0xFFFF9A99)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFFF8F8)
val onBackgroundLight = Color(0xFF23191E)
val surfaceLight = Color(0xFFFFF8F8)
val onSurfaceLight = Color(0xFF23191E)
val surfaceVariantLight = Color(0xFFF7DBE8)
val onSurfaceVariantLight = Color(0xFF54414B)
val outlineLight = Color(0xFF87717C)
val outlineVariantLight = Color(0xFFDAC0CB)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF392D33)
val inverseOnSurfaceLight = Color(0xFFFFECF3)
val inversePrimaryLight = Color(0xFFFFAEDC)
val surfaceDimLight = Color(0xFFE8D5DD)
val surfaceBrightLight = Color(0xFFFFF8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFFF0F5)
val surfaceContainerLight = Color(0xFFFDE9F1)
val surfaceContainerHighLight = Color(0xFFF7E3EB)
val surfaceContainerHighestLight = Color(0xFFF1DDE5)